version: "3.7"
services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: always
        ports:
            - 8888:80
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel
    mysql:
        image: mysql:8.2
        container_name: mysql
        restart: always
        environment:
            - MYSQL_DATABASE=db_roulette
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=admin.root

        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 33069:3306
        networks:
            - laravel
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - .:/var/www/html
        ports:
            - 9000:80
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
